### ISSUE TITLE
请问会开发iOS版本吗

### ISSUE THREAD

**Issue by Walkersifolia** [HMCL-dev/HMCL-PE-CN#101]
目前的安卓手机是用来测一些软件以及抓包方便用的，性能并不是很高，主力机用的还是苹果，想请问一下作者有想法开发iOS版本的吗

**Comment by root-S7** [comment]
不会，因为需要windows没有xcode。且IOS17 +已经干掉侧载一些权限

**Comment by root-S7** [comment]
还有就是，你去用了ios版pojav启动器后你就不想在苹果设备上玩了

**Comment by Walkersifolia** [comment]
> 还有就是，你去用了ios版pojav启动器后你就不想在苹果设备上玩了

pojav launcher我用过，明明是M1，却卡的离谱，我以为是启动器问题（

**Comment by Walkersifolia** [comment]
> 不会，因为需要windows没有xcode。且IOS17 +已经干掉侧载一些权限

明白了，谢谢
