### ISSUE TITLE
外置登录无法使用

### ISSUE THREAD

**Issue by xiamo070091** [HMCL-dev/HMCL-PE-CN#11]
外置登录无法使用，虽然可以在启动器界面添加外置登录用户，但游戏内依然显示登录无效
猜测可能是启动参数里边并没有调用authlib-injector，因为澪有同样的bug，添加上之后就好了
但是HMCL-PE没找到自定义启动参数的选项，非常难受

**Comment by Tungstend** [comment]
emm就是没做完
