### ISSUE TITLE
Why it crashes when i play it 

### ISSUE THREAD

**Issue by Plugina** [HMCL-dev/HMCL-PE-CN#12]
Version: 1.16.5 (Fabric 1.11.5,not Install API and mods)
Java: 1.8.0 (64 bit)
Renderer: gl4es 1.1.5 (OpenGL ES 2.1)
Phone model: Vivo Y85A
Android version: 8.1.0
Processor: Qualcomm Snapdragon Octa Core
RAM: 4G
By the way,plz make it English as much as possible

**Comment by Tungstend** [comment]
Fabric crashes because incorrect arguments,this bug has been fixed but not released yet,u can build it yourself or wait for an update

**Comment by Tungstend** [comment]
We are students,we don't have enough time for translation work.If you or anyone else is willing to help us complete the translation work, you can refer to https://github.com/huanghongxun/HMCL/tree/javafx/HMCL/src/main/resources/assets/lang

**Comment by Plugina** [comment]
> 我们是学生，没有足够的时间翻译工作。如果您或其他人愿意帮助我们完成翻译工作，可以参考[https://github.com/huanghongxun/HMCL/tree/javafx/ HMCL/src/main/resources/assets/lang](https://github.com/huanghongxun/HMCL/tree/javafx/HMCL/src/main/resources/assets/lang)

Ok,I know.Also thanks for your team work hard with this project all time what you are doing;)

**Comment by Tungstend** [comment]
thanks for your support,I will close this issue,if u have any other question,just open a new issue
