### ISSUE TITLE
运行forge版本会崩溃

### ISSUE THREAD

**Issue by localhosts-A** [HMCL-dev/HMCL-PE-CN#13]
使用HMCLPE安装的1.12.2 forge最新版，进入游戏会崩溃;
使用HMCL安装的1.16.5 forge最新版
还有Pojav安装的1.16.5 forge最新版，都会提示下图错误
而运行普通版本则不会有这种情况
![Screenshot_2022-05-04-09-27-38-633_com tungsten hmclpe](https://user-images.githubusercontent.com/69374148/166623287-64842efa-2fba-446e-a642-56255dacc721.jpg)

**Comment by Tungstend** [comment]
1.12的问题没遇到过，1.16.5请务必使用HMCLPE 安装，否则无法启动，另外，版本名称不要设置为1.16.5-forge-36.2.35，否则也可能有问题，最好不要改版本名，默认1.16.5即可

**Comment by localhosts-A** [comment]
确实可以，1.12.2估计是设置问题，HMCLPE到forge安装的时候进度条会卡一下，等待一下就开始安装了
