### ISSUE TITLE
[Bug] Bug Detect

### ISSUE THREAD

**Issue by ssaagamemer** [HMCL-dev/HMCL-PE-CN#17]
Found a Big That Cant Download A Modpack In HMCL-PE 
I Clicked But It Dont Work Any Download Task GUI Didn't Open Or Pop-up

**Comment by Tungstend** [comment]
It's not a bug, it's just not done, this part is a lot of work and I've run into some nasty issues

**Comment by ssaagamemer** [comment]
ok
