### ISSUE TITLE
Login Procress Error

### ISSUE THREAD

**Issue by ssaagamemer** [HMCL-dev/HMCL-PE-CN#18]
I Gona To Play Mc But It Error
Timeout
i cant Get Any Log

**Comment by Tungstend** [comment]
Make sure you are using the 5.13 release or the version built with the latest source code, what type of account are you using to log in?  If it is a Microsoft account, please make sure that you have purchased the Minecraft java edition, and also ensure that your own network is smooth, we have not encountered the problem of being unable to log in, but as far as I know, if the login process fails when starting the game, an error window will pop up, maybe  it will give some information

**Comment by ghost** [comment]
Oh,thanks.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Tungstend** [comment]
Have you solved this problem, if so, I will close this issue
