### ISSUE TITLE
无法登录多个微软账户

### ISSUE THREAD

**Issue by localhosts-A** [HMCL-dev/HMCL-PE-CN#20]
无法登录多个微软账户，但是可以添加离线账户
还有一个小问题:
在第一次进入软件时，正在检查运行库的进度条可能会鬼畜，比如到百分之两千多

**Comment by doxjsic** [comment]
Unable to download, 1.19

**Comment by localhosts-A** [comment]
> 无法登录多个微软账户

**Comment by Enderman-Teleporting** [comment]
我也发现了这个问题,但是没得到很好的回答

**Comment by Enderman-Teleporting** [comment]
#38

**Comment by localhosts-A** [comment]
> 我也发现了这个问题,但是没得到很好的回答

行吧，我这个问题到现在作者也没回
还是我去私聊作者才给了我一个回复
