### ISSUE TITLE
无法游玩远古版（比如b1.7.3）

### ISSUE THREAD

**Issue by sb886886555** [HMCL-dev/HMCL-PE-CN#21]
一直卡在界面
![Screenshot_20220616_064545_com tungsten hmclpe](https://user-images.githubusercontent.com/107589404/173955483-e67fb58b-b4f5-4c0d-ab87-8b119831d47f.jpg)

**Comment by Tungstend** [comment]
有些版本可能需要java7，目前不考虑这些版本
