### ISSUE TITLE
1.12.2闪退

### ISSUE THREAD

**Issue by hmjmfyyds** [HMCL-dev/HMCL-PE-CN#24]
不知为何，Forge+Optifine的1.12.2在3秒之内就闪退
java8可以确定没有问题
1.16.5都可以启动
Forge:14.23.5.2860
Optifine:HD_U_G5
Mod:Poop mod
appleskin
jei
Jorneymap
无材质光影

**Comment by hmjmfyyds** [comment]
再附：1.19的优化mod闪退，整合包安装不了

**Comment by Tungstend** [comment]
/sdcard/Android/data/com.tungsten.hmclpe/files/debug/日志拿来

**Comment by doxjsic** [comment]
I can't download 1 19

**Comment by hmjmfyyds** [comment]
日志文件：
网盘链接:https://pan.baidu.com/s/1_A_mSD9-gxBxlLN7YdWM3A 
提取码:6p11

**Comment by hmjmfyyds** [comment]
链接:https://pan.baidu.com/s/1s2uwecoMxGvdpFdM494daQ 
提取码:2qc5
日志文件

**Comment by hmjmfyyds** [comment]
链接:https://pan.baidu.com/s/1s2uwecoMxGvdpFdM494daQ 
提取码:2qc5
日志

**Comment by hmjmfyyds** [comment]
链接:https://pan.baidu.com/s/1H9KWhxW1J8fooIltZpn-6w 
提取码:w81c
日志文件

**Comment by Tungstend** [comment]
> I can't download 1 19
The download link of 1.19 has changed. This bug has been fixed. Please wait for the update or compile the source code yourself. Of course, compiling the source code requires some minor modifications to the source code.

**Comment by Tungstend** [comment]
> I can't download 1 19

The download link of 1.19 has changed. This bug has been fixed. Please wait for the update or compile the source code yourself. Of course, compiling the source code requires some minor modifications to the source code.

**Comment by DreamOneX** [comment]
> 链接:https://pan.baidu.com/s/1H9KWhxW1J8fooIltZpn-6w 
> 提取码:w81c
> 日志文件

你真优秀，用百度网盘传日志 🤣

**Comment by TSaltedfishKing** [comment]
Source:https://pan.baidu.com/s/1H9KWhxW1J8fooIltZpn-6w Access Token: w81c

`boat_latest_log(1).txt`

>OpenJDK 64-Bit Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
[authlib-injector] [INFO] Logging file: /storage/emulated/0/HMCLPE/.minecraft/versions/1.12.2/authlib-injector.log
[authlib-injector] [INFO] Version: 1.1.45
[authlib-injector] [INFO] Authentication server: https://littleskin.cn/api/yggdrasil/
Error: Could not find or load main class **********@qq.com
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x70d9de5820)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x70d9dea640)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x70d9dea640)

**Comment by TSaltedfishKing** [comment]
说实话，你的日志实在没有什么信息。
