### ISSUE TITLE
关于添加云更新

### ISSUE THREAD

**Issue by lxzcl** [HMCL-dev/HMCL-PE-CN#3]
在pc上的HMCL具有云更新功能，这对一些小白用户非常友好，但是很可惜许多玩家并没有注意到这个功能，这个对服主真的非常方便，
https://www.huangyuhui.net/index.php/2019/11/12/118/
这是pc上的HMCL教程，通过抓取json，同步云ＭＯＤ列表
列：
https://update.mymc.xyz/server-manifest.json
非常希望添加这个功能，手机上真的非常需要这个功能

**Comment by Tungstend** [comment]
很显然我们还有很多更重要的工作要做，这项功能确实在计划之内，但需要过一段时间

**Comment by lxzcl** [comment]
非常感谢你的回答
-------------------------------
hmcl的的ui和功能非常酷炫，个人感觉比澪的ui好多了，在澪是我尝试添加功能可惜他不是开源的，云更新这个功能在手机是期待已久。
还有在电脑上的某些mod在低配手机并不适合用，例如旅行地图，希望添加高配手机选项以同步类似的mod，希望可以参考我的意见，还有类似于即装即用的功能可以实现么？
还有类似于澪的公告，澪的公告采用的是抓取网页txt文件显示在安卓页面上，服主通过反编译可以修改网页url的txt文件地址以实现服主自定义公告，这个功能个人感觉确实有点多余，但是好歹是一个功能聊胜于无，列如玩家进游戏画面异常，但是玩家是新手并不知道通过更改渲染器解决，可以写在公告上，
-----------------------------------
以上是我的建议
在我看来这个程序和项目比澪优秀很多，无论的ui和功能，未来可期。我也希望为项目做出贡献奈何我学习的安卓不太精通。

**Comment by Tungstend** [comment]
公告什么的会已更好的形式呈现，我和澪u作者已经达成合作，共同开发HMCL-PE，模组的事情以后再说了，但是这个启动器一定会比澪u和以前的其他启动器更好

**Comment by Tungstend** [comment]
腐竹们根本不需要反编译，如果他们有能力完全可以自己改源码，会提供一个简单方便的接口，没能力的自然是花钱定制。

**Comment by lxzcl** [comment]
确实，总想着反编译，忘了这是开源的，打扰了，问题关闭
