### ISSUE TITLE
关于boat启动器启动花屏的问题

### ISSUE THREAD

**Issue by naiyQAQ** [HMCL-dev/HMCL-PE-CN#35]
![Screenshot_20220706_170334_com tungsten hmclpe](https://user-images.githubusercontent.com/94218819/177515134-bc4c33b9-cb14-4aff-a38c-6418da26d80a.jpg)
渲染器virglrenderer，游戏版本1.19（用不了gl4es）
#34 似乎被警告了

**Comment by Tungstend** [comment]
渲染错误目前没办法，你可以通过修改分辨率解决具体多少自己试，可能小于一百可能大于一百，我就是109，gpl的问题已经解决
