### ISSUE TITLE
report几个使用时问题

### ISSUE THREAD

**Issue by Enderman-Teleporting** [HMCL-dev/HMCL-PE-CN#38]
1. 版本1.19下载上显示网址错误（待会儿等我确认一下发个错误信息）
2. 整合包无法装载
3. 仅仅能登录一个带有MC正版账号的微软账号

**Comment by Enderman-Teleporting** [comment]
![Uploading Screenshot_20220712_151420_com.tungsten.hmclpe.jpg…]()

**Comment by Enderman-Teleporting** [comment]
![Uploading Screenshot_20220712_151420_com.tungsten.hmclpe.jpg…]()

**Comment by Enderman-Teleporting** [comment]
![Screenshot_20220712_151420_com tungsten hmclpe](https://user-images.githubusercontent.com/100068319/178508296-9d3d9cb9-549e-4321-a5f1-d9a8364ba683.jpg)

**Comment by Tungstend** [comment]
1已经修复，公测没发罢了
2就没做
3不知道啥问题，懒得修，以后会关注的

**Comment by Enderman-Teleporting** [comment]
好吧
