### ISSUE TITLE
Minecraft无法下载

### ISSUE THREAD

**Issue by dontknowhy** [HMCL-dev/HMCL-PE-CN#42]
![Screenshot_20220725_224253.jpg](https://user-images.githubusercontent.com/85813508/180805050-f9865122-ad89-4695-850c-907b40249fd0.jpg)
![Screenshot_20220725_224238.jpg](https://user-images.githubusercontent.com/85813508/180805086-a52784a7-f0b6-4fbe-9046-6bbc255a9e54.jpg)
![Screenshot_20220725_224217.jpg](https://user-images.githubusercontent.com/85813508/180805102-0dcbbaac-dfcf-46f0-8b9e-05db12eb03f0.jpg)
全部权限都给了，连权限狗里边的都给了

**Comment by Tungstend** [comment]
早解决了，公测没发罢了
