### ISSUE TITLE
无法下载Minecraft

### ISSUE THREAD

**Issue by dontknowhy** [HMCL-dev/HMCL-PE-CN#43]
![Screenshot_20220725_224217.jpg](https://user-images.githubusercontent.com/85813508/180932602-55e00e69-dea1-4c03-953a-096fa1ae4690.jpg)
![Screenshot_20220725_224238.jpg](https://user-images.githubusercontent.com/85813508/180932614-e6d48a7d-3d05-4686-b071-880ee4be721f.jpg)
![Screenshot_20220725_224253.jpg](https://user-images.githubusercontent.com/85813508/180932638-d4fb6e2f-e4d9-4730-9efe-3a8881f20259.jpg)

**Comment by Tungstend** [comment]
我他妈之前不是回复过你了啊
