### ISSUE TITLE
English language 

### ISSUE THREAD

**Issue by Yasserpro312** [HMCL-dev/HMCL-PE-CN#45]
add English language

**Comment by ghost** [comment]
Only build beta
![1](https://user-images.githubusercontent.com/78855727/180992575-10150ef1-ede9-4f2e-b597-13313382323d.jpg)

**Comment by Yasserpro312** [comment]
> Only build beta ![1](https://user-images.githubusercontent.com/78855727/180992575-10150ef1-ede9-4f2e-b597-13313382323d.jpg)

thanks

**Comment by Tungstend** [comment]
Next release will support English.
