### ISSUE TITLE
无法下载新版本

### ISSUE THREAD

**Issue by yzh080511** [HMCL-dev/HMCL-PE-CN#48]
![Screenshot_2022-07-29-10-07-17-573_com tungsten hmclpe](https://user-images.githubusercontent.com/91873963/181668512-5accc516-8549-4776-8063-0c37c66828ff.jpg)

**Comment by aaaapai** [comment]
pojav启动器可以下载，但是要正版帐号、好用，储存空间大的手机或已root机

**Comment by Tungstend** [comment]
早解决了，公测没发

**Comment by yzh080511** [comment]
那么请问公测什么时候发布？😂

________________________________
发件人: Tungstend ***@***.***>
发送时间: 2022年7月29日 1:05
收件人: Tungstend/HMCL-PE ***@***.***>
抄送: yzh080511 ***@***.***>; Author ***@***.***>
主题: Re: [Tungstend/HMCL-PE] 无法下载新版本 (Issue #48)


早解决了，公测没发
