### ISSUE TITLE
English is not available in settings

### ISSUE THREAD

**Issue by PanjiCraft28** [HMCL-dev/HMCL-PE-CN#51]
When I open the menu settings > general on HMCL PE in the language section there is no English language. Please add English language 👍🏻

**Comment by ghost** [comment]
你可能用的是公测版，内测版才有

**Comment by Tungstend** [comment]
https://github.com/Tungstend/HMCL-PE/blob/2f2c3e81492c55784c5908fc4e09cb628e89db45/HMCLPE/release/HMCLPE-release.apk?raw=true

Try this

**Comment by zaldhyx77** [comment]
we have to pay 2$ ???
