### ISSUE TITLE
启动游戏错误，明明拥有正版的微软账号显示该账号没有正版MC

### ISSUE THREAD

**Issue by Enderman-Teleporting** [HMCL-dev/HMCL-PE-CN#56]
![Screenshot_20220805_114823_com tungsten hmclpe](https://user-images.githubusercontent.com/100068319/182998106-5bdd574c-d668-4bb9-ac13-ec10e8883aa4.jpg)

**Comment by Stander-Digend** [comment]
有可能是这几点问题：
1.WI-FI不好，建议重试
2.你的账户改密码了，建议重新登录
以上是我的解决办法

**Comment by Enderman-Teleporting** [comment]
我试试

**Comment by Enderman-Teleporting** [comment]
还是不行，我是移动网，网速还行，并且我的账户没改过密码

**Comment by lava191810** [comment]
我记得JAVA和基岩是两个单独的版本，要单独买
有没有可能你的账号只买了基岩版没有买JAVA版

**Comment by Enderman-Teleporting** [comment]
我都有而且有2个账号

**Comment by SungHerobrine97** [comment]
如果确实是说有正版mc却显示“没有正版Minecraft”，烦请用微软号登录到minecraft.net再检查一下。
如果情况属实，你应该去找微软客服把有问题的启动器和运行日志一起上传。
否则，重启手机试试

**Comment by SungHerobrine97** [comment]
参照[这个议题](https://github.com/huanghongxun/HMCL/issues/1544)[和另外一个](https://github.com/huanghongxun/HMCL/issues/1568)

**Comment by Enderman-Teleporting** [comment]
可以了，谢谢
