### ISSUE TITLE
In english version : authorization verification code

### ISSUE THREAD

**Issue by GTR-PR0** [HMCL-dev/HMCL-PE-CN#61]
In english version : authorization verification code
How do I get it?

**Comment by root-S7** [comment]
https://url67.ctfile.com/f/37104367-633122034-3112f6?p=2604

（password：2604）

**Comment by LoranGold** [comment]
> https://url67.ctfile.com/f/37104367-633122034-3112f6?p=2604
> 
> （password：2604）

Thanks Bro❤️

**Comment by wkosh** [comment]
> https://url67.ctfile.com/f/37104367-633122034-3112f6?p=2604
> 
> （password：2604）

bro this is a virus I tried to install and it wasn't hello launcher because my play protect warned that it was a virus and also the application is very light and has no photo

**Comment by root-S7** [comment]
> > https://url67.ctfile.com/f/37104367-633122034-3112f6?p=2604
> > （密码：2604）
> 
> 兄弟，这是我尝试安装的病毒，它不是 hello 启动器，因为我的游戏保护警告说它是病毒，而且应用程序很轻，没有照片

他本身就不是启动器而是获取激活码的

**Comment by wkosh** [comment]
> > > https://url67.ctfile.com/f/37104367-633122034-3112f6?p=2604
> > > （密码：2604）
> > 
> > 
> > 兄弟，这是我尝试安装的病毒，它不是 hello 启动器，因为我的游戏保护警告说它是病毒，而且应用程序很轻，没有照片
> 
> 他本身就不是启动器而是获取激活码的

yes I downloaded it here and it's not a virus but the code generator thanks man ❤️
