### ISSUE TITLE
bad launcher

### ISSUE THREAD

**Issue by Pinecone6442** [HMCL-dev/HMCL-PE-CN#68]
extremely bad

**Comment by wkosh** [comment]
so delete it and don't comment on it if you don't like it

**Comment by WesleyVanNeck** [comment]
Yeah remove it if don't like it don't make useless issues @Pinecone6442

**Comment by WesleyVanNeck** [comment]
@Pinecone6442  you could also tell us your issue and we will help

**Comment by Pinecone6442** [comment]
> @Pinecone6442 you could also tell us your issue and we will help

too many bugs, controls are bad!

**Comment by WesleyVanNeck** [comment]
> > @Pinecone6442 you could also tell us your issue and we will help
> 
> too many bugs, controls are bad!

read the readme it says its unfinished

**Comment by WesleyVanNeck** [comment]
> > @Pinecone6442 you could also tell us your issue and we will help
> 
> too many bugs, controls are bad!

also thats your opinian but dont bother use with it
