### ISSUE TITLE
请求添加交换跳跃与潜行，优化渲染

### ISSUE THREAD

**Issue by Stander-Digend** [HMCL-dev/HMCL-PE-CN#72]

**Comment by root-S7** [comment]
前两个可能可行，最后一个想屁吃

**Comment by Tungstend** [comment]
渲染在优化了，交换跳跃潜行自定义一个不就行了。。

**Comment by BuleBaby1402** [comment]
自定义的跳跃和潜行交替不能滑动，我想要想基岩版的那种（上下可以滑动，指可以从一个按键滑到另一个按键，起到边走边跳）

**Comment by Stander-Digend** [comment]
> 渲染在优化了，交换跳跃潜行自定义一个不就行了。。

不不不自定义的没法用，我想要基岩版的那种，就是可以上下滑动，hmclpe的自定义按键不能从一个按键滑到另一个按键（建议直接加个十字键中间是跳跃这个设定）
