### ISSUE TITLE
无法使用微软登录

### ISSUE THREAD

**Issue by WutzuBert** [HMCL-dev/HMCL-PE-CN#8]
网页无法打开
位于 https://login.live.com/........... 的网页无法加载，因为：
net::ERR_PROXY_CONNECTION_FAILED

但是Chrome可以打开登录链接，但是不能登录启动器

**Comment by DreamOneX** [comment]
你的代理无法连接，建议检查浏览器/系统设置，**这与HMCL-PE无关**
