### ISSUE TITLE
安装forge后无法正常启动游戏

### ISSUE THREAD

**Issue by block13566** [HMCL-dev/HMCL-PE-CN#82]
机型是redmi note10用的是github上开源的HMCLPE，我目前已经卸载重装尝试了从所有地方下载的到的HMCLPE了，但是安装forge后无法正常启动游戏，我已经确保不会出现Java8这种低级错误了，原版也能正常启动，但是一旦安装forge后就算是没有安装任何mod也无法启动

我不知道要怎么附上日志🤔

**Comment by root-S7** [comment]
导出日志文件发出来并附上录屏。不会发附件云盘分享也行。

**Comment by block13566** [comment]
> 导出日志文件发出来并附上录屏。不会发附件云盘分享也行。

现在我找到解决办法了，用一个版本比较低的forge就行了🤔

**Comment by block13566** [comment]
> 导出日志文件发出来并附上录屏。不会发附件云盘分享也行。

https://wwm.lanzouv.com/i8Svz0ejk63i这里是log
