### ISSUE TITLE
无法启动1.19.3

### ISSUE THREAD

**Issue by MineCreeper86** [HMCL-dev/HMCL-PE-CN#93]
手机型号：Honor 8X
启动1.15成功，但是1.19.3进入等待界面后白屏并闪退到启动器主界面

**Comment by MineCreeper86** [comment]
打开记录log但是没有任何log

**Comment by root-S7** [comment]
https://github.com/huanghongxun/HMCL-PE/issues/149#issuecomment-1399209316

**Comment by GithubDyy** [comment]
你可以重启手机或将手机进行恢复出厂设置，或者是清理手机缓存。如果不行请跟我联系，我的邮箱是dingyiyi20231@outlook.com

**Comment by MineCreeper86** [comment]
这个问题已经解决了（其实我去用pojav然后把jre17-x8664搞上才能用的）
